apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-fastapi-app 
  description: A scaffolded Python web application
  github.com/project-slug: pep8speaks-org/pep8speaks
spec:
  type: service
  lifecycle: experimental
  owner: team:devops
